/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as ParaQuemRouteImport } from './routes/para-quem'
import { Route as OrgaosPublicosRouteImport } from './routes/orgaos-publicos'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DiferenciaisRouteImport } from './routes/diferenciais'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaQuemRoute = ParaQuemRouteImport.update({
  id: '/para-quem',
  path: '/para-quem',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgaosPublicosRoute = OrgaosPublicosRouteImport.update({
  id: '/orgaos-publicos',
  path: '/orgaos-publicos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiferenciaisRoute = DiferenciaisRouteImport.update({
  id: '/diferenciais',
  path: '/diferenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/orgaos-publicos': typeof OrgaosPublicosRoute
  '/para-quem': typeof ParaQuemRoute
  '/plataforma': typeof PlataformaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/orgaos-publicos': typeof OrgaosPublicosRoute
  '/para-quem': typeof ParaQuemRoute
  '/plataforma': typeof PlataformaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/orgaos-publicos': typeof OrgaosPublicosRoute
  '/para-quem': typeof ParaQuemRoute
  '/plataforma': typeof PlataformaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/cursos'
    | '/demonstracao'
    | '/diferenciais'
    | '/empresas'
    | '/escolas'
    | '/orgaos-publicos'
    | '/para-quem'
    | '/plataforma'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/cursos'
    | '/demonstracao'
    | '/diferenciais'
    | '/empresas'
    | '/escolas'
    | '/orgaos-publicos'
    | '/para-quem'
    | '/plataforma'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/cursos'
    | '/demonstracao'
    | '/diferenciais'
    | '/empresas'
    | '/escolas'
    | '/orgaos-publicos'
    | '/para-quem'
    | '/plataforma'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRoute
  DemonstracaoRoute: typeof DemonstracaoRoute
  DiferenciaisRoute: typeof DiferenciaisRoute
  EmpresasRoute: typeof EmpresasRoute
  EscolasRoute: typeof EscolasRoute
  OrgaosPublicosRoute: typeof OrgaosPublicosRoute
  ParaQuemRoute: typeof ParaQuemRoute
  PlataformaRoute: typeof PlataformaRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-quem': {
      id: '/para-quem'
      path: '/para-quem'
      fullPath: '/para-quem'
      preLoaderRoute: typeof ParaQuemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgaos-publicos': {
      id: '/orgaos-publicos'
      path: '/orgaos-publicos'
      fullPath: '/orgaos-publicos'
      preLoaderRoute: typeof OrgaosPublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diferenciais': {
      id: '/diferenciais'
      path: '/diferenciais'
      fullPath: '/diferenciais'
      preLoaderRoute: typeof DiferenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRoute,
  DemonstracaoRoute: DemonstracaoRoute,
  DiferenciaisRoute: DiferenciaisRoute,
  EmpresasRoute: EmpresasRoute,
  EscolasRoute: EscolasRoute,
  OrgaosPublicosRoute: OrgaosPublicosRoute,
  ParaQuemRoute: ParaQuemRoute,
  PlataformaRoute: PlataformaRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
